---

- name: Ensure git installed
  apt:
    name: git
    state: present
  tags: [ drupal-scripts, install ]

- name: Sync drupal-scripts
  git:
    repo: https://github.com/viasite/drupal-scripts.git
    version: "{{ drupal_scripts_version }}"
    dest: "{{ drupal_scripts_install_path }}"
    force: yes
  tags: [ drupal-scripts, install, upgrade ]

- name: Create executable link for drs
  file:
    src: "{{ drupal_scripts_install_path }}/bin/drs"
    dest: /usr/local/bin/drs
    state: link
  tags: [ drupal-scripts, install ]

- name: drupal-scripts config
  template:
    src: drupal-scripts.conf.j2
    dest: /etc/drupal-scripts.conf
    owner: root
    group: root
    mode: 0644
  tags: [ drupal-scripts, install, configure ]

- name: drupal-scripts-users config
  template:
    src: drupal-scripts-users.conf.j2
    dest: "{{ drupal_scripts_users_list_file }}"
    owner: root
    group: root
    mode: 0644
  tags: [ drupal-scripts, install, configure ]
